/**
 * @fileoverview JavaScript code generator for KUHUL.
 *
 * Lowers a GeometricIR to a self-contained JavaScript ES module.
 *
 * @module kuhul/compiler/codegen/js-codegen
 */

import { BaseCodegen } from '../codegen.js';
import { GeometricIR }  from '../../ir/ir-types.js';

// ------------------------------------------------------------------ //
// Glyph → JS operation mapping
// ------------------------------------------------------------------ //

const GLYPH_OPS = {
  '⊗': (ops) => `kuhul_matmul(${ops.join(', ')})`,
  '⊕': (ops) => `(${ops.join(' + ')})`,
  '⊖': (ops) => `(${ops.join(' - ')})`,
  '⊛': (ops) => `kuhul_conv(${ops.join(', ')})`,
  '⊜': (ops) => `kuhul_eq(${ops.join(', ')})`,
  '⊝': (ops) => `(-${ops[0]})`,
  '⊞': (ops) => `kuhul_concat(${ops.join(', ')})`,
};

// ------------------------------------------------------------------ //
// JavaScriptCodegen
// ------------------------------------------------------------------ //

/** Generates JavaScript code from a GeometricIR program. */
export class JavaScriptCodegen extends BaseCodegen {
  /**
   * @param {GeometricIR} ir
   * @returns {string}
   */
  generate(ir) {
    const lines = [];

    lines.push('// Generated by KUHUL JavaScript Codegen');
    lines.push('// DO NOT EDIT');
    lines.push('');
    lines.push(this._emitRuntime());
    lines.push('');
    lines.push('export async function run(ctx = {}) {');
    lines.push('  const mem = Object.create(null);');
    lines.push('  Object.assign(mem, ctx);');
    lines.push('');

    let indent = 2;

    for (const instr of ir.instructions) {
      const pad = ' '.repeat(indent);
      switch (instr.opcode) {
        case 'ALLOC': {
          const [name, elemType, shape] = instr.operands;
          const size = shape.reduce((a, d) => a * (d === '?' ? 1 : d), 1);
          lines.push(`${pad}mem["${name}"] = new Float32Array(${size}); // ${elemType}[${shape}]`);
          break;
        }
        case 'READ': {
          const [name] = instr.operands;
          lines.push(`${pad}const _r_${name} = mem["${name}"];`);
          break;
        }
        case 'WRITE': {
          const [target, val] = instr.operands;
          const valExpr = this._renderOperand(val);
          lines.push(`${pad}mem["${target}"] = ${valExpr};`);
          break;
        }
        case 'OP': {
          const [glyph, ...operands] = instr.operands;
          const ops   = operands.map(o => this._renderOperand(o));
          const fn    = GLYPH_OPS[glyph];
          const expr  = fn ? fn(ops) : `kuhul_op("${glyph}", ${ops.join(', ')})`;
          lines.push(`${pad}const _op_result = ${expr};`);
          break;
        }
        case 'CALL': {
          const [fnName, ...args] = instr.operands;
          const argStr = args.map(a => this._renderOperand(a)).join(', ');
          lines.push(`${pad}await kuhul_call("${fnName}", ${argStr});`);
          break;
        }
        case 'CONST': {
          const [val] = instr.operands;
          lines.push(`${pad}const _const = ${val};`);
          break;
        }
        case 'FOLD_START':
          lines.push(`${pad}{`);
          indent += 2;
          break;
        case 'FOLD_END':
          indent = Math.max(2, indent - 2);
          lines.push(`${' '.repeat(indent)}}`);
          break;
        case 'PHASE_START':
          lines.push(`${pad}for (let _phase = 0; _phase < 2 * Math.PI; _phase += Math.PI / 8) {`);
          indent += 2;
          break;
        case 'PHASE_END':
          indent = Math.max(2, indent - 2);
          lines.push(`${' '.repeat(indent)}}`);
          break;
        default:
          lines.push(`${pad}// unknown opcode: ${instr.opcode}`);
      }
    }

    lines.push('');
    lines.push('  return mem;');
    lines.push('}');

    return lines.join('\n');
  }

  // ---------------------------------------------------------------- //
  // Minimal runtime helpers
  // ---------------------------------------------------------------- //

  _emitRuntime() {
    return [
      '// --- KUHUL JS runtime helpers ---',
      'function kuhul_matmul(a, b) {',
      '  if (!(a instanceof Float32Array) || !(b instanceof Float32Array)) return new Float32Array(0);',
      '  return a; // placeholder: real matmul would use typed-array math',
      '}',
      'function kuhul_conv(a, b) { return a; }',
      'function kuhul_eq(a, b)   { return a; }',
      'function kuhul_concat(...args) { return args[0]; }',
      'async function kuhul_call(fn, ...args) {}',
    ].join('\n');
  }
}
