// K'UHUL++ JavaScript Code Generator
// Emits runnable JavaScript from a Geometric IR program.
// The output uses plain ES modules and Float32Arrays for tensor operations.

import type { GeometricIR, IRInstruction, GlyphOp } from '../../ir/ir-types.js';

// ------------------------------------------------------------------ //
// JSCodegen
// ------------------------------------------------------------------ //

/**
 * Generates a JavaScript module string from a Geometric IR program.
 * The emitted code is self-contained and exports a `kuhulMain` function.
 *
 * @example
 * const cg = new JSCodegen();
 * const js = cg.generate(ir);
 * // Write to file or eval in a Worker
 */
export class JSCodegen {
    private indentLevel = 0;
    private lines: string[]  = [];

    /**
     * Generate JavaScript source for the given IR.
     *
     * @param ir - Geometric IR from `generateIR()`
     * @returns ES module source string
     */
    generate(ir: GeometricIR): string {
        this.lines = [];
        this.indentLevel = 0;

        this.emitHeader(ir);
        this.emitRuntimeHelpers();
        this.emit('');
        this.emitFunction('export async function kuhulMain(env = {})', () => {
            this.emit(`// Manifold: ${ir.manifold.dimensions}D, metric=${ir.manifold.metric}`);
            this.emit(`let __phase = ${ir.manifold.phase.toFixed(6)};`);
            this.emit(`const __mem = new Map();`);
            this.emit('');

            for (const instr of ir.instructions) {
                this.lowerInstruction(instr);
            }

            this.emit('');
            this.emit('return { phase: __phase, memory: __mem };');
        });

        return this.lines.join('\n') + '\n';
    }

    // ---- Emission helpers ----

    private emit(line: string): void {
        const pad = '  '.repeat(this.indentLevel);
        this.lines.push(line === '' ? '' : pad + line);
    }

    private emitFunction(sig: string, body: () => void): void {
        this.emit(`${sig} {`);
        this.indentLevel++;
        body();
        this.indentLevel--;
        this.emit('}');
    }

    private emitHeader(ir: GeometricIR): void {
        this.emit(`// K'UHUL++ Generated JavaScript Module`);
        this.emit(`// Manifold: ${ir.manifold.dimensions}D, metric=${ir.manifold.metric}`);
        this.emit(`// Phase range: 0..2π, initial=${ir.manifold.phase.toFixed(4)}`);
        this.emit(`// Phases: ${ir.phases.map(p => p.name).join(', ') || '(none)'}`);
        this.emit(`// Generated by JSCodegen`);
        this.emit('');
    }

    private emitRuntimeHelpers(): void {
        this.emit('// ---- Runtime helpers ----');
        this.emit('');

        this.emitFunction('function __geoProduct(a, b)', () => {
            this.emit(`// ⊗ element-wise multiply`);
            this.emit(`const out = new Float32Array(Math.min(a.length, b.length));`);
            this.emit(`for (let i = 0; i < out.length; i++) out[i] = a[i] * b[i];`);
            this.emit(`return out;`);
        });
        this.emit('');

        this.emitFunction('function __geoTranslate(a, b)', () => {
            this.emit(`// ⊕ element-wise add`);
            this.emit(`const out = new Float32Array(Math.min(a.length, b.length));`);
            this.emit(`for (let i = 0; i < out.length; i++) out[i] = a[i] + b[i];`);
            this.emit(`return out;`);
        });
        this.emit('');

        this.emitFunction('function __geoDifference(a, b)', () => {
            this.emit(`// ⊖ element-wise subtract`);
            this.emit(`const out = new Float32Array(Math.min(a.length, b.length));`);
            this.emit(`for (let i = 0; i < out.length; i++) out[i] = a[i] - b[i];`);
            this.emit(`return out;`);
        });
        this.emit('');

        this.emitFunction('function __applyGlyph(glyph, left, right)', () => {
            this.emit(`const lv = typeof left  === 'number' ? new Float32Array([left])  : left;`);
            this.emit(`const rv = typeof right === 'number' ? new Float32Array([right]) : right;`);
            this.emit(`switch (glyph) {`);
            this.emit(`  case '⊗': return __geoProduct(lv, rv);`);
            this.emit(`  case '⊕': return __geoTranslate(lv, rv);`);
            this.emit(`  case '⊖': return __geoDifference(lv, rv);`);
            this.emit(`  case '⊞': return __geoTranslate(lv, rv);`);
            this.emit(`  default:  return lv;`);
            this.emit(`}`);
        });
    }

    // ---- IR instruction lowering ----

    private lowerInstruction(instr: IRInstruction): void {
        const i = instr as any;
        switch (instr.op) {
            case 'const':
                if (typeof i.value === 'string') {
                    this.emit(`const ${i.id} = ${JSON.stringify(i.value)};`);
                } else {
                    this.emit(`const ${i.id} = ${i.value};`);
                }
                break;

            case 'load':
                this.emit(`const ${i.id} = __mem.get(${JSON.stringify(i.name)}) ?? env[${JSON.stringify(i.name)}];`);
                break;

            case 'store':
                this.emit(`__mem.set(${JSON.stringify(i.name)}, ${i.src});`);
                break;

            case 'alloc':
                this.emit(`const ${i.id} = new Float32Array(0); // alloc`);
                break;

            case 'invoke': {
                const args = (i.args as string[]).join(', ');
                this.emit(`const ${i.id} = (typeof ${i.callee} === 'function') ? ${i.callee}(${args}) : undefined;`);
                break;
            }

            case 'phase':
                this.emit(`__phase = (__phase + ${i.delta}) % (2 * Math.PI);`);
                break;

            case 'label':
                this.emit(`/* label: ${i.name} */`);
                break;

            case 'branch':
                this.emit(`/* branch → ${i.target} */`);
                break;

            case 'condbranch':
                this.emit(`/* condbranch ${i.cond} ? ${i.ifTrue} : ${i.ifFalse} */`);
                break;

            case 'return':
                if (i.value) {
                    this.emit(`return ${i.value};`);
                } else {
                    this.emit(`return;`);
                }
                break;

            default:
                // Glyph ops
                if (this.isGlyphOp(instr.op)) {
                    this.emit(`const ${i.id} = __applyGlyph('${instr.op}', ${i.left}, ${i.right});`);
                } else {
                    this.emit(`/* unknown op: ${instr.op} */`);
                }
                break;
        }
    }

    private isGlyphOp(op: string): op is GlyphOp {
        return ['⊗','⊕','⊖','⊛','⊜','⊝','⊞','⤍','↻','⟲','∿','⊙','≋'].includes(op);
    }
}
