/**
 * @fileoverview WebAssembly (WAT text format) code generator for KUHUL.
 *
 * Lowers a GeometricIR to a WebAssembly Text Format (WAT) module.
 * The output can be assembled with `wat2wasm` or the WABT toolkit.
 *
 * @module kuhul/compiler/codegen/wasm-codegen
 */

import { BaseCodegen } from '../codegen.js';
import { GeometricIR }  from '../../ir/ir-types.js';

// ------------------------------------------------------------------ //
// WasmCodegen
// ------------------------------------------------------------------ //

/** Generates WebAssembly Text Format (WAT) code from a GeometricIR. */
export class WasmCodegen extends BaseCodegen {
  /**
   * @param {GeometricIR} ir
   * @returns {string} WAT source
   */
  generate(ir) {
    const lines = [];
    lines.push('(module');
    lines.push('  ;; Generated by KUHUL WasmCodegen');
    lines.push('');

    // Memory declaration (1 page = 64 KiB)
    lines.push('  (memory (export "memory") 1)');
    lines.push('');

    // Build symbol → memory-offset table
    const offsets = new Map();
    let offset = 0;
    for (const instr of ir.instructions) {
      if (instr.opcode === 'ALLOC') {
        const [name, , shape] = instr.operands;
        const bytes = shape.reduce((a, d) => a * (d === '?' ? 1 : d), 1) * 4;
        offsets.set(name, offset);
        lines.push(`  ;; ${name} @ offset ${offset}, ${bytes} bytes`);
        offset += bytes;
      }
    }
    lines.push('');

    // Main run function
    lines.push('  (func (export "run")');

    // Local variable declarations (one f32 per unique write target)
    const locals = new Set();
    for (const instr of ir.instructions) {
      if (instr.opcode === 'WRITE') locals.add(instr.operands[0]);
      if (instr.opcode === 'READ')  locals.add(instr.operands[0]);
    }
    for (const name of locals) {
      lines.push(`    (local $${name} f32)`);
    }
    lines.push('');

    for (const instr of ir.instructions) {
      switch (instr.opcode) {
        case 'ALLOC':
          lines.push(`    ;; alloc ${instr.operands[0]}`);
          break;
        case 'READ': {
          const [name] = instr.operands;
          const off = offsets.get(name) ?? 0;
          lines.push(`    (local.set $${name} (f32.load (i32.const ${off})))`);
          break;
        }
        case 'WRITE': {
          const [target, val] = instr.operands;
          const off = offsets.get(target) ?? 0;
          const valInstr = typeof val === 'number'
            ? `(f32.const ${val})`
            : `(local.get $${val})`;
          lines.push(`    (f32.store (i32.const ${off}) ${valInstr})`);
          break;
        }
        case 'OP': {
          const [glyph, a, b] = instr.operands;
          const aInstr = typeof a === 'number' ? `(f32.const ${a})` : `(local.get $${a})`;
          const bInstr = typeof b === 'number' ? `(f32.const ${b})` : b ? `(local.get $${b})` : '';
          switch (glyph) {
            case '⊕': lines.push(`    (f32.add ${aInstr} ${bInstr})`); break;
            case '⊖': lines.push(`    (f32.sub ${aInstr} ${bInstr})`); break;
            case '⊗': lines.push(`    (f32.mul ${aInstr} ${bInstr})`); break;
            case '⊝': lines.push(`    (f32.neg ${aInstr})`);           break;
            default:  lines.push(`    ;; glyph ${glyph} not natively supported in WAT`); break;
          }
          break;
        }
        case 'FOLD_START':  lines.push('    (block'); break;
        case 'FOLD_END':    lines.push('    )'); break;
        case 'PHASE_START': lines.push('    (loop $phase_loop'); break;
        case 'PHASE_END':   lines.push('    )'); break;
        default:
          lines.push(`    ;; ${instr.opcode}(${instr.operands.join(', ')})`);
      }
    }

    lines.push('  )');
    lines.push(')');

    return lines.join('\n');
  }
}
