/**
 * @fileoverview WebGPU / WGSL code generator for KUHUL.
 *
 * Lowers a GeometricIR to WGSL (WebGPU Shading Language) compute shaders.
 *
 * @module kuhul/compiler/codegen/webgpu-codegen
 */

import { BaseCodegen } from '../codegen.js';
import { GeometricIR }  from '../../ir/ir-types.js';

// ------------------------------------------------------------------ //
// Glyph → WGSL operation mapping
// ------------------------------------------------------------------ //

const GLYPH_WGSL = {
  '⊕': (a, b) => `(${a} + ${b})`,
  '⊖': (a, b) => `(${a} - ${b})`,
  '⊗': (a, b) => `(${a} * ${b})`,
  '⊝': (a)    => `(-${a})`,
  '⊛': (a, b) => `kuhul_conv(${a}, ${b})`,
  '⊜': (a, b) => `(${a} == ${b})`,
  '⊞': (a, b) => `kuhul_concat(${a}, ${b})`,
};

// ------------------------------------------------------------------ //
// WebGPUCodegen
// ------------------------------------------------------------------ //

/** Generates WGSL compute shader code from a GeometricIR. */
export class WebGPUCodegen extends BaseCodegen {
  /**
   * @param {GeometricIR} ir
   * @returns {string} WGSL source
   */
  generate(ir) {
    const lines = [];
    lines.push('// Generated by KUHUL WebGPU Codegen');
    lines.push('// WGSL compute shader');
    lines.push('');

    // Build storage bindings from the symbol table
    let bindingIndex = 0;
    const bindings = new Map();

    for (const instr of ir.instructions) {
      if (instr.opcode === 'ALLOC') {
        const [name, , shape] = instr.operands;
        const size = shape.reduce((a, d) => a * (d === '?' ? 1 : d), 1);
        bindings.set(name, { binding: bindingIndex++, size });
      }
    }

    // Emit storage buffer bindings
    for (const [name, info] of bindings) {
      lines.push(`@group(0) @binding(${info.binding})`);
      lines.push(`var<storage, read_write> ${name}: array<f32, ${info.size}>;`);
      lines.push('');
    }

    // Compute shader entry point
    lines.push('@compute @workgroup_size(64)');
    lines.push('fn main(@builtin(global_invocation_id) gid: vec3<u32>) {');
    lines.push('  let idx = gid.x;');
    lines.push('');

    for (const instr of ir.instructions) {
      switch (instr.opcode) {
        case 'ALLOC':
          lines.push(`  // alloc ${instr.operands[0]}`);
          break;
        case 'READ': {
          const [name] = instr.operands;
          lines.push(`  var ${name}_val = ${name}[idx];`);
          break;
        }
        case 'WRITE': {
          const [target, val] = instr.operands;
          const valExpr = typeof val === 'number' ? String(val) : `${val}_val`;
          lines.push(`  ${target}[idx] = ${valExpr};`);
          break;
        }
        case 'OP': {
          const [glyph, ...operands] = instr.operands;
          const ops  = operands.map(o => typeof o === 'number' ? String(o) : `${o}_val`);
          const fn   = GLYPH_WGSL[glyph];
          const expr = fn ? fn(...ops) : `/* glyph ${glyph} */ ${ops[0]}`;
          lines.push(`  let _op_result = ${expr};`);
          break;
        }
        case 'PHASE_START':
          lines.push('  for (var _phase: f32 = 0.0; _phase < 6.2832; _phase += 0.3927) {');
          break;
        case 'PHASE_END':
          lines.push('  }');
          break;
        case 'FOLD_START': lines.push('  {'); break;
        case 'FOLD_END':   lines.push('  }'); break;
        default:
          lines.push(`  // ${instr.opcode}(${instr.operands.join(', ')})`);
      }
    }

    lines.push('}');
    return lines.join('\n');
  }
}
