"""
{{ID}}.bots.py — Model-specific inference bot for {{NAME}} micronaut.

Generated by scaffold_micronaut.py. Customize:
  - System prompt (from @agent.main.system_prompt in the .xjson)
  - Tools list (matches model_api_registry.json tools)
  - Backend loader (auto-selected by scaffold based on @model.core.backend)
  - Fold identifier (added to _MICRONAUT_TO_FOLD in orchestrator_bot.py)

Native deps (co-located micronaut_native.py bridge):
  micronaut_todo_creator.hpp → TodoCreator, TodoItem, TodoJsonSerializer
  deterministic_v6.h         → DeterministicV6, TraceLogger

DO NOT modify the BotOrchestrator interface (stream/infer/dispatch/status).
"""

import os
import json
import logging
import sys as _sys
import time as _time
from pathlib import Path
from typing import Iterator, Optional

logger = logging.getLogger(__name__)

# ─── Native bridge (micronaut_native.py, co-located) ─────────────────────────
_sys.path.insert(0, str(Path(__file__).parent))
try:
    from micronaut_native import (  # type: ignore
        TodoCreator, TodoItem, TodoJsonSerializer,
        DeterministicV6, TraceLogger, NATIVE_AVAILABLE,
    )
    _NATIVE_BRIDGE = True
    _trace_logger  = TraceLogger(str(Path(__file__).parent / "{{ID}}_trace.jsonl"))
    _todo_creator  = TodoCreator("{{ID}}")
except ImportError:
    _NATIVE_BRIDGE = False
    _trace_logger  = None
    _todo_creator  = None

# ─── Fold / Identity ─────────────────────────────────────────────────────────
MICRONAUT_ID   = "{{ID}}"
MICRONAUT_NAME = "{{NAME}}"
MICRONAUT_FOLD = "⟁{{FOLD}}_FOLD⟁"

# ─── Tools (must match model_api_registry.json tools array) ──────────────────
TOOLS = [
    {{TOOLS_LIST}}
]

# ─── System Prompt ───────────────────────────────────────────────────────────
SYSTEM_PROMPT = """{{SYSTEM_PROMPT}}"""

# ─── Model Core (loaded from .xjson @model.core) ─────────────────────────────
_XJSON_PATH = Path(__file__).parent / f"{MICRONAUT_ID}.xjson"

def _load_model_core() -> dict:
    if _XJSON_PATH.exists():
        with open(_XJSON_PATH) as f:
            data = json.load(f)
        return data.get("@model.core", {})
    return {}


# ─── Backend Loader ───────────────────────────────────────────────────────────
{{BACKEND_BLOCK}}


# ─── Bot Interface ────────────────────────────────────────────────────────────
class {{CLASS_NAME}}Bot:
    """
    {{NAME}} micronaut bot.

    Implements the standard BotOrchestrator interface:
      - stream(prompt, context)  → Iterator[str]  (token chunks)
      - infer(prompt, context)   → str            (complete response)
      - dispatch(task)           → dict           (task result + metadata)
      - status()                 → dict           (health/config info)
    """

    def __init__(self):
        self.model_core = _load_model_core()
        self._backend = _init_backend(self.model_core)
        self.fold = MICRONAUT_FOLD
        self.id   = MICRONAUT_ID

    def stream(self, prompt: str, context: Optional[list] = None) -> Iterator[str]:
        """Stream response tokens for the given prompt."""
        messages = _build_messages(prompt, context)
        yield from _stream_backend(self._backend, self.model_core, messages)

    def infer(self, prompt: str, context: Optional[list] = None) -> str:
        """Return complete response for the given prompt."""
        return "".join(self.stream(prompt, context))

    def dispatch(self, task: dict) -> dict:
        """
        Dispatch a structured task from the BotOrchestrator.

        task format:
          { "action": "<tool_name>", "input": "<prompt or args>", "context": [...] }
        """
        action  = task.get("action", "infer")
        prompt  = task.get("input", "")
        context = task.get("context", [])

        if action not in TOOLS and action != "infer":
            return {
                "status": "error",
                "error": f"Unknown action '{action}'. Available: {TOOLS}",
                "fold": self.fold,
            }

        try:
            response = self.infer(prompt, context)
            return {
                "status": "ok",
                "output": response,
                "action": action,
                "fold": self.fold,
                "micronaut": self.id,
            }
        except Exception as e:
            logger.exception(f"[{self.id}] dispatch error")
            return {
                "status": "error",
                "error": str(e),
                "fold": self.fold,
                "micronaut": self.id,
            }

    def status(self) -> dict:
        """Return health and configuration info."""
        backend_type = self.model_core.get("backend", "unknown")
        return {
            "id":      self.id,
            "name":    MICRONAUT_NAME,
            "fold":    self.fold,
            "backend": backend_type,
            "tools":   TOOLS,
            "healthy": self._backend is not None,
        }


# ─── Message Builder ─────────────────────────────────────────────────────────
def _build_messages(prompt: str, context: Optional[list]) -> list:
    """Build message list with system prompt + optional context + user prompt."""
    messages = []
    if context:
        messages.extend(context)
    messages.append({"role": "user", "content": prompt})
    return messages


# ─── Singleton accessor ──────────────────────────────────────────────────────
_bot_instance: Optional["{{CLASS_NAME}}Bot"] = None

def get_bot() -> "{{CLASS_NAME}}Bot":
    global _bot_instance
    if _bot_instance is None:
        _bot_instance = {{CLASS_NAME}}Bot()
    return _bot_instance


# ─── CLI smoke-test ──────────────────────────────────────────────────────────
if __name__ == "__main__":
    import sys
    prompt = " ".join(sys.argv[1:]) if len(sys.argv) > 1 else "Hello, who are you?"
    bot = get_bot()
    print(f"[{bot.id} | {bot.fold}]")
    print(f"Status: {bot.status()}")
    print(f"\nPrompt: {prompt}")
    print("Response: ", end="", flush=True)
    for chunk in bot.stream(prompt):
        print(chunk, end="", flush=True)
    print()
