// pi_field.wgsl — π-KUHUL root system field evolution
// v_i^{t+1} = Σ_j  w_j · sin(π · v_j)   [φ-attractor branch for H3/H4]
// Nodes: 52  |  Generated by pi_kuhul_roots.py

struct Params {
    node_count : u32,
    edge_count : u32,
    step       : u32,
    pi_time    : f32,
};

@group(0) @binding(0) var<storage, read>       nodes_in  : array<f32>;
@group(0) @binding(1) var<storage, read>       weights   : array<f32>;
@group(0) @binding(2) var<storage, read>       edges     : array<vec2<u32>>;
@group(0) @binding(3) var<storage, read_write> nodes_out : array<f32>;
@group(0) @binding(4) var<uniform>             params    : Params;

const PHI : f32 = 1.6180339887;

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) id : vec3<u32>) {
    let i = id.x;
    if (i >= params.node_count) { return; }

    var sum : f32 = 0.0;

    for (var e = 0u; e < params.edge_count; e++) {
        let edge = edges[e];

        // Forward edge j→i (accumulate field at i)
        if (edge.y == i) {
            let j = edge.x;
            let w = weights[j];
            let v = nodes_in[j];
            
    // φ-node: nonlinear attractor (H3/H4 unfoldings)
    if (w > 1.5) {
        sum += w * sin(1.6180339887 * 3.14159265358979 * v);
    } else {
        sum += w * sin(3.14159265358979 * v);
    }
        }

        // Backward suppression (exchange matrix B: negative direction)
        if (edge.x == i) {
            let j = edge.y;
            let w = weights[j];
            let v = nodes_in[j];
            sum -= 0.1 * w * sin(3.14159265358979 * v);
        }
    }

    // Global π-time modulation
    sum = sum * (1.0 + 0.05 * sin(params.pi_time));

    nodes_out[i] = sum;
}
